### ISSUE TITLE
Czy możecie opublikować klienta jako paczkę MVN'a?

### ISSUE THREAD

**Issue by marcin-chwedczuk** [SerwerSMSpl/serwersms-java-api#3]
Standardem obecnej jest budowanie aplikacji za pomocą Mavena lub Gradle (włączając w to zarządzanie zależnościami).
Generalnie dodawanie pliku JAR gdy używa się powyższych narzędzie jest rozumiane jako antywzorzec.
Fajnie było by mieć kod klienta jako paczkę Maven'a, nie wymaga to dużego wysiłku: http://tutorials.jenkov.com/maven/publish-to-central-maven-repository.html

**Comment by SerwerSMSpl** [comment]
Dzień dobry,  ​   dziękujemy za zgłoszenie. Postaramy się zaktualizować bibliotekę.        Pozdrawiamy Dział IT | Wsparcie techniczne E: bok@serwersms.pl    
                           
                            Dnia
                            pt, 5 Luty o 11:40 AM
                            ,  SerwerSMSpl/serwersms-java-api <reply@reply.github.com>  napisał(-a):
                             

 Standardem obecnej jest budowanie aplikacji za pomocą Mavena lub Gradle (włączając w to zarządzanie zależnościami). 

Generalnie dodawanie pliku JAR gdy używa się powyższych narzędzie jest rozumiane jako antywzorzec. 

Fajnie było by mieć kod klienta jako paczkę Maven'a, nie wymaga to dużego wysiłku: http://tutorials.jenkov.com/maven/publish-to-central-maven-repository.html

**Comment by SerwerSMSpl** [comment]
<dependency>
    <groupId>pl.serwersms</groupId>
    <artifactId>apiv2</artifactId>
    <version>1.1</version>
</dependency>

**Comment by SerwerSMSpl** [comment]
`
<dependency>
    <groupId>pl.serwersms</groupId>
    <artifactId>apiv2</artifactId>
    <version>1.1</version>
</dependency>
`
